version: "3.7"
services:
  caller:
    build:
      context: ./
      dockerfile: ./caller/Dockerfile
    volumes:
      - ./caller:/home/app/pirates:z
      - ./audio:/audio:z
    cap_add:
      - NET_ADMIN
    networks:
      pirates-network:
        ipv4_address: ${IP_CALLER}
    command: >
      bash -c "cd /home/app/pirates
      && cmake . && make &&
      ./bin/caller -c ${IP_CALLER}
      -s ${MESSAGE_SIZE}
      -r ${NUM_ROUNDS}
      -e ${IP_RELAY}"
  #worker:
  #  build:
  #    context: ./
  #    dockerfile: ./worker/Dockerfile
  #  volumes:
  #    - ./worker:/home/app/pirates:z
  #  cap_add:
  #    - NET_ADMIN
  #  networks:
  #    pirates-network:
  #      ipv4_address: ${IP_WORKER}
  #  command: >
  #    bash -c "cd /home/app/pirates
  #    && cmake . && make &&
  #    ./bin/worker -w ${IP_WORKER}"
  #relay:
  #  build:
  #    context: ./
  #    dockerfile: ./relay/Dockerfile
  #  volumes:
  #    - ./relay:/home/app/pirates:z
  #  cap_add:
  #    - NET_ADMIN
  #  networks:
  #    pirates-network:
  #      ipv4_address: ${IP_RELAY}
  #  command: >
  #    bash -c "cd /home/app/pirates
  #    && cmake . && make &&
  #    ./bin/relay"
networks:
  pirates-network:
    ipam:
      config:
        - subnet: ${SUBNET}
