version: "3.7"
services:
  caller:
    build:
      context: ./
      dockerfile: ./caller/Dockerfile
    volumes:
      - ./caller:/home/app/pirates:z
      - ./FastPIR:/home/app/pirates/FastPIR:z
      - ./audio:/audio:z
      - ./logs:/logs:z
    cap_add:
      - NET_ADMIN
    networks:
      pirates-network:
        ipv4_address: ${IP_CALLER}
    command: >
      bash -c "cd /home/app/pirates
      && cmake -DCMAKE_BUILD_TYPE=Release . && make &&
      ./bin/caller 
      -o ${IP_CALLER}
      -r ${NUM_ROUNDS}
      -s ${SNIPPET_SIZE}
      -g ${GROUP_SIZE}
      -u ${NUM_USERS}
      -x ${RUN_ID}
      -n ${IP_RELAY}"
    init: true
  callee:
    build:
      context: ./
      dockerfile: ./callee/Dockerfile
    volumes:
      - ./callee:/home/app/pirates:z
      - ./FastPIR:/home/app/pirates/FastPIR:z
  #    - ./audio:/audio:z
      - ./logs:/logs:z
    cap_add:
      - NET_ADMIN
    networks:
      pirates-network:
        ipv4_address: ${IP_CALLEE}
    command: >
      bash -c "cd /home/app/pirates
      && cmake -DCMAKE_BUILD_TYPE=Release . && make &&
      ./bin/callee 
      -o ${IP_CALLEE}
      -r ${NUM_ROUNDS}
      -s ${SNIPPET_SIZE}
      -g ${GROUP_SIZE}
      -u ${NUM_USERS}
      -x ${RUN_ID}"
    init: true
  worker:
    build:
      context: ./
      dockerfile: ./worker/Dockerfile
    volumes:
      - ./worker:/home/app/pirates:z
      - ./FastPIR:/home/app/pirates/FastPIR:z
      - ./logs:/logs:z
    cap_add:
      - NET_ADMIN
    networks:
      pirates-network:
        ipv4_address: ${IP_WORKER}
    command: >
      bash -c "cd /home/app/pirates
      && cmake -DCMAKE_BUILD_TYPE=Release . && make &&
      ./bin/worker 
      -o ${IP_WORKER}
      -r ${NUM_ROUNDS}
      -s ${SNIPPET_SIZE}
      -g ${GROUP_SIZE}
      -u ${NUM_USERS}
      -x ${RUN_ID}
      -n ${IP_CALLEE}"
    init: true
  relay:
    build:
      context: ./
      dockerfile: ./relay/Dockerfile
    volumes:
      - ./relay:/home/app/pirates:z
      - ./FastPIR:/home/app/pirates/FastPIR:z
      - ./logs:/logs:z
    cap_add:
      - NET_ADMIN
    networks:
      pirates-network:
        ipv4_address: ${IP_RELAY}
    command: >
      bash -c "cd /home/app/pirates
      && cmake -DCMAKE_BUILD_TYPE=Release . && make &&
      ./bin/relay
      -o ${IP_RELAY}
      -r ${NUM_ROUNDS}
      -s ${SNIPPET_SIZE}
      -g ${GROUP_SIZE}
      -u ${NUM_USERS}
      -x ${RUN_ID}
      -n ${IP_WORKER}"
    init: true
networks:
  pirates-network:
    ipam:
      config:
        - subnet: ${SUBNET}
